const app = Vue.createApp({})
app.component('modal', Modal)
app.component('todo-form', TodoForm)
app.component('todo-item', TodoItem)
app.component('categories-panel', CategoriesPanel)
app.component('calendar-view', CalendarView)
app.component('todo-list', TodoList)
app.mount('#app')
